apiVersion: v1
kind: PersistentVolume
metadata:
  name: rosa-pv-100m
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rosa-manual
  hostPath:
    path: /mnt/rosa-pv
    type: DirectoryOrCreate
