apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rosa-claim
  namespace: rosa-lab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: rosa-manual
