apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-service.fullname" . }}-config
  labels:
    {{- include "my-service.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config | nindent 2 }}
