apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-values
data:
  replicaCount: {{ .Values.replicaCount | quote }}
  config: |
    {{- toYaml .Values.config | nindent 4 }}
  featureFlags: |
    {{- toYaml .Values.featureFlags | nindent 4 }}
  global-environment: {{ .Values.global.environment | quote }}
  global-domain: {{ .Values.global.domain | quote }}
