apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore }}
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-db      # ESO가 만들 K8s Secret 이름
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.remoteKey }}
