apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: rosa-lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: hashicorp/http-echo:1.0
          args:
            - -text=hello
            - -listen=:8080
          ports:
            - containerPort: 8080
