dbPassword: ENC[AES256_GCM,data:RRXtupyvjXQe,iv:uzcZt90f3TB5TXhwP7uR0OB2B8nSZUQ4UxjPS2HVNNw=,tag:jUwxSEkBtneOmm2xk1QQTA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TERsQVdDV1RmT294Q3F1
            VkExUXdRaTBoZVN1V0tiWlcyRDVialh3VmdBClBQMjgyQ2JpOG9xMXhoMXNyTnJq
            ZE04U2w4RE5ROGw3YVlxemluOGIzVGsKLS0tIFZnWjczZEdpbnQzTW5ZUmpYdTQ4
            YzRpNi9vYUs0VTlxNEZrdHdIaFpNdmcKHGXOn2zAmXgzAKsVzdRe7Y/gfGXAiEWz
            badeWam8uEQpnKCBUMiGtyefjJJ85mSc5kP2fmuZ8OREGFapL/fbtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1djxpdfs63nadw2qclk7v0mh2rcjmx4mhqx85fqf0hzjpkwk4meysxae8mx
    lastmodified: "2026-07-01T05:42:05Z"
    mac: ENC[AES256_GCM,data:fthFs2ni8ZglZm4Qa1D965lZAGh2hvE3Hu7kzG8N3RZldZiejowCGJO/+MLnDDXy/gEOO62+Mu2IyUPmx+kaSfNRwyzVP4N3Vcbcn9ok28k/RuELiCdLWOoiT9+FR2xGQw0rKS8OrIUncYScUm0J5ok74F3mNP9pGpJvlL/CGZ8=,iv:LKbPm4ukAJhEE0mtxnfsyBZCQcQu5EVNT6d6vqz7D80=,tag:74eYCxY0JbkCJtR/Uz5Kow==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
