apiVersion: v1
kind: Pod
metadata:
  name: memory-volume
  namespace: rosa-lab
spec:
  containers:
    - name: app
      image: busybox:1.37
      command: ["sleep", "3600"]
      volumeMounts:
        - name: ram
          mountPath: /ram
  volumes:
    - name: ram
      emptyDir:
        medium: Memory
        sizeLimit: 32Mi
