apiVersion: v1
kind: Pod
metadata:
  name: app-retain
  namespace: rosa-lab
spec:
  containers:
    - name: app
      image: busybox:1.37
      command: ["sleep", "3600"]
      volumeMounts:
        - name: store
          mountPath: /data
  volumes:
    - name: store
      persistentVolumeClaim:
        claimName: retain-claim
